apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xhuui2ljs-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xhuui2ljs-java-springboot-gitops